# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 646)
        MainWindow.setStyleSheet("background-color:white;\n"
"border-radius:10px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.info = QtWidgets.QTextBrowser(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(300, 180, 511, 331))
        self.info.setObjectName("info")
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(1092, 10, 51, 28))
        self.close_btn.setStyleSheet("\n"
"#close_btn{\n"
"\n"
"border:none;\n"
"}\n"
"#close_btn:hover{\n"
"    padding-bottom:10px;\n"
"}")
        self.close_btn.setObjectName("close_btn")
        self.mini = QtWidgets.QPushButton(self.centralwidget)
        self.mini.setGeometry(QtCore.QRect(1050, 10, 40, 31))
        self.mini.setMaximumSize(QtCore.QSize(40, 40))
        self.mini.setStyleSheet("background-image: url(:/img/F:/download/mini.png);\n"
"background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain;  /* 或 cover / 100px 100px */")
        self.mini.setText("")
        self.mini.setObjectName("mini")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close_btn.setText(_translate("MainWindow", "关闭"))
