# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 624)
        MainWindow.setMinimumSize(QtCore.QSize(180, 20))
        MainWindow.setStyleSheet("background-color:transparent;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 90, 281, 431))
        self.frame.setStyleSheet("#frame{\n"
"\n"
"background-color: qconicalgradient(cx:0.5, cy:0.517, angle:0, stop:0 rgba(0, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 40, 101, 51))
        self.label.setStyleSheet("#label{\n"
"font-size:30px;\n"
"font: 30pt \"幼圆\";\n"
"line-hright: 30px;\n"
"}")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(380, 100, 300, 411))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color:white;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: rgba(255, 255, 255,0);\n"
"    border: none;\n"
"    color:gray;\n"
"    border-bottom: 1px solid gray;\n"
"}\n"
"QLineEdit:focus{\n"
"border-bottom: 1px solid red;\n"
"height: 35px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.close_btn = QtWidgets.QPushButton(self.frame_2)
        self.close_btn.setGeometry(QtCore.QRect(190, 10, 93, 28))
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.close_btn.setStyleSheet("#close_btn:hover{\n"
"    padding-bottom: 10px;\n"
"    color:green;\n"
"}")
        self.close_btn.setObjectName("close_btn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 241, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userId = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.userId.setStyleSheet("")
        self.userId.setInputMask("")
        self.userId.setText("")
        self.userId.setObjectName("userId")
        self.verticalLayout.addWidget(self.userId)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password.setWhatsThis("")
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.login = QtWidgets.QPushButton(self.frame_2)
        self.login.setGeometry(QtCore.QRect(100, 290, 93, 28))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.login.setStyleSheet("#thread_work{border-radius: 10px;\n"
"border: 1px solid gray;}\n"
"#thread_work:hover{\n"
"    border: 1px solid red;\n"
"}")
        self.login.setObjectName("thread_work")
        self.frame_2.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "登陆"))
        self.close_btn.setText(_translate("MainWindow", "关闭"))
        self.userId.setPlaceholderText(_translate("MainWindow", "请输入账号"))
        self.password.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.login.setText(_translate("MainWindow", "登陆"))
